name: Run Tests on Merge

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  numbfs_utils_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build

      - name: Build project
        run: |
          meson setup build
          ninja -C build

      - name: Run tests
        run: |
          cd build
          meson test
